services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  meilisearch:
    image: "getmeili/meilisearch:v1.7"
    volumes:
      - ./meilisearch:/data.ms
    ports:
      - "7700:7700"
  mongodb:
    image: "mongo:latest"  
    ports:
      - "27017:27017" 
volumes:
 mongodb_data_container:
